# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0097_auto_20180722_0804"),
        ("pretix_sofort", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencedsoforttransaction",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pretixbase.OrderPayment",
            ),
        ),
    ]
