# Generated by Django 5.2.12 on 2026-07-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_sofort", "0002_referencedsoforttransaction_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReferencedSofortTransaction",
        ),
    ]
